routes/web.php
<?php
//Route::get('/', function () {
//    return view('welcome');
//});
//测试首页
Route::get('/', 'PagesController@root')->name('root');
//make:auth 自带用户认证
// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

//修改个人页面路由
Route::resource('users', 'UsersController', ['only' => ['show', 'edit', 'update']]);
Route::resource('topics', 'TopicsController', ['only' => ['index', 'create', 'store', 'update', 'edit', 'destroy']]);
//分类下的话题列表
Route::resource('categories', 'CategoriesController', ['only' => ['show']]);
//上传图片
Route::post('upload_image', 'TopicsController@uploadImage')->name('topics.upload_image');
//seo
Route::get('topics/{topic}/{slug?}', 'TopicsController@show')->name('topics.show');
Route::resource('replies', 'RepliesController', ['only' => [ 'store','destroy']]);
//显示通知
Route::resource('notifications', 'NotificationsController', ['only' => ['index']]);
//非法访问警告
Route::get('permission-denied', 'PagesController@permissionDenied')->name('permission-denied');

app/Models/User.php
<?php

namespace App\Models;

use Auth;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    //需在 User 中使用 laravel-permission 提供的 Trait —— HasRoles，
    //此举能让我们获取到扩展包提供的所有权限和角色的操作方法。
    use HasRoles;
    //use Notifiable;
    use Notifiable {
        notify as protected laravelNotify;
    }

    public function notify($instance)
    {
        //通知用户为作者不通知
        if ($this->id == Auth::id()) {
            return;
        }
        //每当你调用 $user->notify() 时， users 表里的 notification_count 将自动 +1。
        $this->increment('notification_count');
        //发送给定的通知。
        $this->laravelNotify($instance);
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'introduction', 'avatar',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    //一用户可以拥有多条话题
    //关联设置成功后，我们即可使用 $user->topics 来获取到用户发布的所有话题数据
    public function topics()
    {
        return $this->hasMany(Topic::class);
    }

    //是否文章作者
    public function isAuthorOf($model)
    {
        return $this->id == $model->user_id;
    }

    //一个用户可以发布很多评论
    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    //清除已读的消息
    public function markAsRead()
    {
        $this->notification_count = 0;
        $this->save();
        $this->unreadNotifications->markAsRead();
    }

    //后台修改密码
    public function setPasswordAttribute($value)
    {
        // 如果值的长度等于 60，即认为是已经做过加密的情况
        if (strlen($value) != 60) {

            // 不等于 60，做密码加密处理
            $value = bcrypt($value);
        }

        $this->attributes['password'] = $value;
    }
    //后台修改头像
    public function setAvatarAttribute($path)
    {
        // 如果不是 `http` 子串开头，那就是从后台上传的，需要补全 URL
        //确定给定字符串是否以给定的子字符串开头。
        if ( ! starts_with($path, 'http')) {

            // 拼接完整的 URL
            $path = config('app.url') . "/uploads/images/avatars/$path";
        }

        $this->attributes['avatar'] = $path;
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\Handlers\ImageUploadHandler;
use App\Http\Requests\UserRequest;
use App\Models\User;
use Illuminate\Http\Request;

//个人页面
class UsersController extends Controller
{
    public function __construct()
    {
        //未登录只有查看的权限
        $this->middleware('auth', ['except' => ['show']]);
    }

    //
    public function show(User $user)
    {
        //用户对象变量 $user 通过 compact 方法转化为一个关联数组，
        //并作为第二个参数传递给 view 方法，将变量数据传递到视图中。
        return view('users.show', compact('user'));
    }

    //编辑
    public function edit(User $user)
    {
        $this->authorize('update',$user);
        return view('users.edit', compact('user'));
    }

    //更新
    public function update(UserRequest $request, User $user, ImageUploadHandler $uploader)
    {
        //dd($request->avatar);
        $this->authorize('update',$user);
        $data = $request->all();
        if ($request->avatar) {
            $result = $uploader->save($request->avatar, 'avatars', $user->id, 362);
            if ($result) {
                $data['avatar'] = $result['path'];
            }
        }
        $user->update($data);
        return redirect()->route('users.show', $user->id)->with('success', '更新个人资料成功');
    }
}

resources/views/users/_replies.blade.php
@if (count($replies))

    <ul class="list-group">
        @foreach ($replies as $reply)
            <li class="list-group-item">
                <a href="{{ $reply->topic->link(['#reply' . $reply->id]) }}">
                    {{ $reply->topic->title }}
                </a>

                <div class="reply-content" style="margin: 6px 0;">
                    {!! $reply->content !!}
                </div>

                <div class="meta">
                    <span class="glyphicon glyphicon-time" aria-hidden="true"></span> 回复于 {{ $reply->created_at->diffForHumans() }}
                </div>
            </li>
        @endforeach
    </ul>

@else
    <div class="empty-block">暂无数据 ~_~ </div>
@endif

{{-- 分页 --}}
{!! $replies->appends(Request::except('page'))->render() !!}

resources/views/users/_topics.blade.php
@if(count($topics))
    <ul class="list-group">
        @foreach($topics as $topic)
            <li class="list-group-item">
                <a href="{{$topic->link()}}">
                    {{$topic->title}}
                </a>
                <span class="meta pull-right">
                    {{$topic->reply_count}}回复
                    <span>.</span>
                    {{$topic->created_at->diffForHumans()}}
                </span>
            </li>
        @endforeach
    </ul>
@else
    <div class="empty-block">~~无数据~~</div>
@endif
{{--分页--}}
{!! $topics->render() !!}

resources/views/users/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="panel panel-default col-md-10 col-md-offset-1">
            <div class="panel-heading">
                <h4>
                    <i class="glyphicon glyphicon-edit"></i>编辑个人资料
                </h4>
            </div>
            {{--错误提示--}}
            @include('common.error')
            <div class="panel-body">
                <form action="{{route('users.update',$user->id)}}" method="post" enctype="multipart/form-data" accept-charset="UTF-8">
                    {{--更新方法--}}
                    <input type="hidden" name="_method" value="PUT">
                    <input type="hidden" name="_token" value="{{csrf_token()}}">

                    <div class="form-group">
                        <label for="name-field">用户名</label>
                        <input type="text" class="form-control" name="name" id="name-field"
                               value="{{old('name',$user->name)}}">
                    </div>
                    <div class="form-group">
                        <label for="email-field">邮 箱</label>
                        <input type="text" class="form-control" name="email" id="email-field"
                               value="{{old('email',$user->email)}}">
                    </div>
                    <div class="form-group">
                        <label for="introduction-field">个人简介</label>
                        <textarea name="introduction" id="introduction-field" class="form-control"
                                  rows="3">{{ old('introduction', $user->introduction) }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="" class="avatar-label">头 像</label>
                        <input type="file" name="avatar">

                        @if($user->avatar)
                            <br>
                            <img src="{{$user->avatar}}" alt="" class="thumbnail img-responsive" width="200px">
                        @endif
                    </div>
                    <div class="well well-sm">
                        <button type="submit" class="btn btn-primary">保存</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@stop

resources/views/users/show.blade.php
@extends('layouts.app')
@section('title',$user->name.'的个人中心')
@section('content')
    {{--个人中心页面--}}
    <div class="row">
        <div class="col-lg-3 col-md-3 hidden-sm hidden-xs user-info">
            <div class="panel panel-default">
                <div class="panel-body">
                    {{--media  图文混排--}}
                    <div class="media">
                        <div align="center">
                            <img
                                src="{{$user->avatar}}"
                                alt="" width="300px" height="300px" class="thumbnail img-responsive">
                        </div>
                        <div class="media-body">
                            <hr>
                            <h4><strong>个人介绍</strong></h4>
                            <p>{{$user->introduction}}</p>
                            <hr>
                            <h4><strong>注册于</strong></h4>
                            <p>{{$user->created_at->diffForHumans()}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
            <div class="panel panel-default">
                <div class="panel-body">
                        <span>
                            <h1 class="panel-title pull-left" style="font-size: 30px;">{{$user->name}}
                                <small>{{$user->email}}</small></h1>
                        </span>
                </div>
            </div>
            <hr>
            {{--发布的内容--}}
            <div class="panel panel-default">
                <div class="panel-body">
                    {{--暂无数据--}}
                    <ul class="nav nav-tabs">
                        <li class="{{active_class(if_query('tab',null))}}">
                            <a href="{{route('users.show',$user->id)}}">Ta 的话题</a></li>
                        <li class="{{active_class(if_query('tab','replies'))}}">
                            <a href="{{route('users.show',[$user->id,'tab'=>'replies'])}}">Ta 的回复</a></li>
                    </ul>
                    @if (if_query('tab', 'replies'))
                        @include('users._replies', ['replies' => $user->replies()->with('topic')->recent()->paginate(5)])
                    @else
                        @include('users._topics', ['topics' => $user->topics()->recent()->paginate(5)])
                    @endif
                </div>
            </div>
        </div>
    </div>
@stop