routes/web.php
<?php
//Route::get('/', function () {
//    return view('welcome');
//});
//测试首页
Route::get('/', 'PagesController@root')->name('root');
//make:auth 自带用户认证
// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

//修改个人页面路由
Route::resource('users', 'UsersController', ['only' => ['show', 'edit', 'update']]);
Route::resource('topics', 'TopicsController', ['only' => ['index', 'create', 'store', 'update', 'edit', 'destroy']]);
//分类下的话题列表
Route::resource('categories', 'CategoriesController', ['only' => ['show']]);
//上传图片
Route::post('upload_image', 'TopicsController@uploadImage')->name('topics.upload_image');
//seo
Route::get('topics/{topic}/{slug?}', 'TopicsController@show')->name('topics.show');
Route::resource('replies', 'RepliesController', ['only' => [ 'store','destroy']]);
//显示通知
Route::resource('notifications', 'NotificationsController', ['only' => ['index']]);
//非法访问警告
Route::get('permission-denied', 'PagesController@permissionDenied')->name('permission-denied');

resources/views/layouts/_footer.blade.php
<footer class="footer">
    {{--底部模版--}}
    <div class="container">
        {{--左边--}}
        <p class="pull-left">
            By <a href="" target="_blank">李志行</a><span style="color: #e27575;font-size: 14px;">❤</span>
        </p>
        {{--右边--}}
        <p class="pull-right"><a href="mailto:{{setting('contact_email')}}">联系我</a></p>
    </div>
</footer>

resources/views/layouts/_header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#app-navbar-collapse">
                <span class="sr-only">切换导航</span>
                {{--icon-bar图标栏--}}
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            {{--品牌形象--}}
            <a class="navbar-brand" href="{{url('/')}}">
                Laravel-Blog
            </a>
        </div>

        <div class="collapse navbar-collapse">
            {{--左导航--}}
            <ul class="nav navbar-nav">
                <li class="{{ active_class(if_route('topics.index')) }}"><a href="{{ route('topics.index') }}">话题</a>
                </li>
                <li class="{{ active_class((if_route('categories.show') && if_route_param('category', 1))) }}"><a
                        href="{{ route('categories.show', 1) }}">分享</a></li>
                <li class="{{ active_class((if_route('categories.show') && if_route_param('category', 2))) }}"><a
                        href="{{ route('categories.show', 2) }}">教程</a></li>
                <li class="{{ active_class((if_route('categories.show') && if_route_param('category', 3))) }}"><a
                        href="{{ route('categories.show', 3) }}">问答</a></li>
                <li class="{{ active_class((if_route('categories.show') && if_route_param('category', 4))) }}"><a
                        href="{{ route('categories.show', 4) }}">公告</a></li>
            </ul>
            {{--右导航--}}
            <ul class="nav navbar-nav navbar-right">
                {{--权限认证--}}
                @guest
                    <li><a href="{{route('login')}}">登录</a></li>
                    <li><a href="{{route('register')}}">注册</a></li>
                @else
                    {{--新建话题链接--}}
                    <li>
                        <a href="{{route('topics.create')}}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                        </a>
                    </li>
                    {{--消息通知--}}
                    <li>
                        <a href="{{route('notifications.index')}}" class="notifications-badge"
                           style="margin-top: -2px;">
                        <span class="badge badge-{{Auth::user()->notification_count>0? 'hint':'fade'}}" title="消息通知">
                            {{Auth::user()->notification_count}}
                        </span>
                        </a>
                    </li>
                    <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                         <span class="user-avatar pull-left" style="margin-right:8px; margin-top:-5px;">
                                <img
                                    src="{{Auth::user()->avatar}}"
                                    class="img-responsive img-circle" width="30px" height="30px">
                            </span>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>
                        {{--下拉菜单--}}
                        <ul class="dropdown-menu" role="menu">
                            @can('manage_contents')
                                <li>
                                    <a href="{{ url(config('administrator.uri')) }}">
                                        <span class="glyphicon glyphicon-dashboard" aria-hidden="true"></span>
                                        管理后台
                                    </a>
                                </li>
                            @endcan
                            <li>
                                <a href="{{route('users.show',Auth::id())}}">
                                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                                    个人中心
                                </a>
                            </li>
                            <li>
                                <a href="{{route('users.edit',Auth::id())}}">
                                    <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                                    编辑资料
                                </a>
                            </li>
                            <li>
                                <a href="{{route('logout')}}"
                                   onclick="event.preventDefault();
                                   document.getElementById('logout-form').submit()">
                                    <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>
                                    退出
                                </a>
                                <form action="{{route('logout')}}" id="logout-form" method="post" style="display: none">
                                    {{csrf_field()}}
                                </form>
                            </li>
                        </ul>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/_message.blade.php
@if(Session::has('message'))
    <div class="alert alert-info">
        <button aria-hidden="true" type="button" class="close" data-dismiss="alert">
        </button>
        {{Session::get('message')}}
    </div>
@endif
@if(Session::has('success'))
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        </button>
        {{Session::get('success')}}
    </div>
@endif
@if(Session::has('danger'))
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        </button>
        {{Session::get('danger')}}
    </div>
@endif

resources/views/layouts/app.blade.php
<!doctype html>
{{--获取默认的语言=>app.php中的locale--}}
<html lang="{{app()->getLocale()}}}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{csrf_token()}}">
    <title>@yield('title','laravel-blog') -{{setting('site_name','Laravel-bbs')}}</title>
    <meta name="description" content="@yield('description',setting('seo_description'), 'LaraBBS')" />
    <meta name="keyword" content="@yield('keyword', setting('seo_keyword', 'LaraBBS,社区,论坛,开发者论坛'))" />
    {{--style--}}
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
    @yield('styles')
    {{--公共模版--}}
</head>
<body>
<div id="app" class="{{route_class()}}-page">
    @include('layouts._header')
    <div class="container">
        {{--消息提示--}}
        @include('layouts._message')
        @yield('content')
    </div>
    @include('layouts._footer')
</div>
{{--sudo-su插件--}}
@if (app()->isLocal())
    @include('sudosu::user-selector')
@endif
{{--script--}}
<script src="{{asset('js/app.js')}}"></script>
@yield('scripts')
</body>
</html>